### ISSUE TITLE
Logo update

### ISSUE THREAD

**Issue by DaliusStuoka** [remotestorage/design#3]
Hey guys,

I've been working on those design updates to Gilli's concept.

I've tried making it geometrically perfect using a hexagon as a base - attaching it below.

![remote-storage-updates](https://cloud.githubusercontent.com/assets/11648283/9064476/f77b34ce-3acc-11e5-9447-2e671a2a1a76.png)

**Comment by silverbucket** [comment]
Looks great! I prefer the non-shaded one, for simplicity and flexibility. +1

**Comment by raucao** [comment]
Very nice!

**Comment by gregkare** [comment]
I can feel the shaded version is going to look amazing in large sizes (x256, x512) :+1:

**Comment by DaliusStuoka** [comment]
Hey guys,

thanks for the positive feedback! Any other versions/variations/changes you'd like me to make to this concept for comparison? Feel free to share your ideas.

Regards,
Dalius

**Comment by raucao** [comment]
@DaliusStuoka: We had a little remoteStorage meeting in Berlin the other day and everybody was happy with the logo exactly as it is now.

One thing that came up was that we probably also need a fitting type to go with it, as the existing one (visible e.g. on https://remotestorage.io in the corner) is likely not a good candidate to re-use. Maybe you already had something in mind?

**Comment by raucao** [comment]
So, I forgot to say this probably means that it'd be good if you could add the necessary files (SVG is the most important I think) to this repo now. You can also just put a link up and someone with Git set up can add it to the actual repository.

**Comment by DaliusStuoka** [comment]
Hey guys, thanks for the update - that's great news. I'll work on some typeface options for you. Regards, Dalius

**Comment by raucao** [comment]
Fantastic!

**Comment by raucao** [comment]
Added the SVG to this repo: https://github.com/remotestorage/design/blob/master/logo-new/icon.svg

**Comment by DaliusStuoka** [comment]
Hello guys,

Here are some of the better options for the typeface I came up with (attached).

Please let me know if you have a preferance out of these.

Regards,
Dalius

![remotestorage_type3](https://cloud.githubusercontent.com/assets/11648283/9512530/dc03e8bc-4c83-11e5-9855-937a109766bc.png)
![remotestorage_type2](https://cloud.githubusercontent.com/assets/11648283/9512532/dc05c772-4c83-11e5-915b-84f92dcf8927.png)
![remotestorage_type1](https://cloud.githubusercontent.com/assets/11648283/9512531/dc052092-4c83-11e5-8147-f4c4a2028a2b.png)

**Comment by raucao** [comment]
I like number 2.

**Comment by galfert** [comment]
Right now im leaning towards 3. But I'm not 100% sure yet.

**Comment by gregkare** [comment]
Nice! I also like number 2, especially for the lowercase r and g

**Comment by silverbucket** [comment]
I like #2 as well, (also #1)

**Comment by raucao** [comment]
Looking at it again, I might tend towards #1 even. Needs moar opinions. :)

@gillisig What do you think?

Also, everyone feel free to propose your own types, of course. If you do, please do so with an inline image, so it's easy to compare all of them.

**Comment by jancborchardt** [comment]
Wow @DaliusStuoka, that looks awesome! Really cool R and S combination in the logo.

I think typeface 1 is definitely the best. 2 and 3 both have too many details which distract and clash with the very unique logo style, while 1 is smooth, legible and keeps in the background.

I also like the plain orange logo best. The shaded one might be cool as version for larger banners or special use, but then the shading needs to be corrected because it seems a bit excessive.

Great work! :) (Cheers from the designer of the original remoteStorage logo back then. Am very happy for this cool update.)

**Comment by gillisig** [comment]
Yeah I guess I like #1 best. Its got a nice friendly feel to it.

**Comment by jancborchardt** [comment]
Also @gillisig awesome work on your part. :) Great collab here folks!

**Comment by DaliusStuoka** [comment]
Hey guys, thanks so much for the feedback! 

I have one question - would it be ok with you if I shared this project on my portfolio showcases (behance, dribbble etc.) when we're done? I'm really liking how this is turning out :-)

**Comment by silverbucket** [comment]
Of course, that's totally fine:)

**Comment by jancborchardt** [comment]
Oh right, an important thing would be that the typeface of the logo is openly licensed. (And the logo itself too of course, like CC-BY as the original is.)

**Comment by raucao** [comment]
Right, that's important. Otherwise we can't use them across the whole project and beyond (in apps etc).

**Comment by gregkare** [comment]
![dscn5793](https://cloud.githubusercontent.com/assets/43297/9994977/14c8bd2a-6080-11e5-8166-7cff34649a7e.jpg)

**Comment by raucao** [comment]
![great-success](https://cloud.githubusercontent.com/assets/842/9995277/3829fdf8-6079-11e5-827f-55bf0f25eb68.jpg)

**Comment by gillisig** [comment]
Nice! The sticker is looking damn good! 

I would like one that is inverted so I can stick it over the apple logo on my macbook and make it glow! :smiley:

**Comment by raucao** [comment]
There was a company in Cologne doing that. I don't remember the name. /cc @Bumi

**Comment by silverbucket** [comment]
Hooray! Looks great!

**Comment by jancborchardt** [comment]
Yeah, cool new sticker! :)

**Comment by bumi** [comment]
@skddc a cologne based company was doing what? stickers? http://www.stixta.com

**Comment by raucao** [comment]
That was exactly it. Thanks! :)

Edit: sent an inquiry.

**Comment by raucao** [comment]
![appcache_orange](https://cloud.githubusercontent.com/assets/842/10048666/f8dca440-620b-11e5-8409-23b2e411c29e.jpg)
![appcache_schwarz](https://cloud.githubusercontent.com/assets/842/10048665/f8c50b1e-620b-11e5-809f-c27cd46b6caa.jpg)

**Comment by gregkare** [comment]
Damn, that looks really good

**Comment by raucao** [comment]
Which one would you put on yours? :)

Also, apparently 11" MBAs have smaller Apples. They explicitly state that they can accommodate those, too.

**Comment by gregkare** [comment]
I like both but I lean towards the black one. I'd need the regular size, I don't have a 11" anymore :)

**Comment by raucao** [comment]
@gillisig Black or orange?

**Comment by DaliusStuoka** [comment]
Those images look great guys!

**Comment by jancborchardt** [comment]
@skddc looks great, except that the circle is a bit big in proportion to the logo. I’d either make the circle smaller – or if that’s needed to cover the apple, make the logo a bit larger.

**Comment by raucao** [comment]
@jancborchardt That's coming from the company. I'm sure they want to both cover the Apple as well as use all available illuminated space.

**Comment by gillisig** [comment]
@skddc awesome! Thats exactly what I was thinking :smile: I think they both look great. But if I had to choose I guess I would go with the black one.

**Comment by jancborchardt** [comment]
@skddc ah, right! Yeah, I’d also go with the black one. Was thinking in my head about maybe white background, and putting an orange hexagon around the logo, but that’s too much I guess.

**Comment by galfert** [comment]
I like the black one better as well.

**Comment by raucao** [comment]
I may or may not have ordered 10 of those to Berlin just now. :)

**Comment by gregkare** [comment]
![big_lebowski_dance](https://cloud.githubusercontent.com/assets/43297/10104179/8299bebe-63a8-11e5-96c1-e024abcd4414.gif)

**Comment by gunar** [comment]
Great work, guys. Logo looks amazing! o/

I like the 1st font best. It looks very professional and reliable. Perhaps it needs a slight hand-adjusted letter-spacing? once again, is it free?

**Comment by gillisig** [comment]
Thanks @skddc, @gregkare and @galfert. The sticker is looking awesome! 

![img_6991](https://cloud.githubusercontent.com/assets/5390864/12561092/3f4d72d8-c396-11e5-8eb7-b4990094bc12.JPG)

**Comment by raucao** [comment]
w00t, that looks fantastic!

**Comment by raucao** [comment]
We have some left, by the way. Whoever wants one should ping me. ;)

/cc @DaliusStuoka

**Comment by DaliusStuoka** [comment]
Well done guys :-) Looks great!

**Comment by palant** [comment]
While the stickers look great, did the discussion on typefaces come to a conclusion? I'd like to offer remoteStorage as an option in a browser extension and the logo isn't known enough to work on its own.

**Comment by raucao** [comment]
No, there's still not logo typeface/text. I think nobody terribly missed one so far.

So basically just use whatever font your extension uses in the first place and integrate it as normal text. The new connect widget spells it "RemoteStorage" in the choosing dialog:

![screenshot from 2018-03-29 11-10-05](https://user-images.githubusercontent.com/842/38080446-c3e07eb0-3341-11e8-9785-d76605ac54c4.png)
