### ISSUE TITLE
Logo license is outdated

### ISSUE THREAD

**Issue by palant** [remotestorage/design#4]
The license statement in this repository currently says:

> remoteStorage logo: Jan-Christoph Borchardt, licensed under Creative Commons Attribution Share-Alike

Now it appears that this applies to the original logo, not to the current one which wasn't created by @jancborchardt but by @DaliusStuoka from what I can tell.

Regardless, is it really necessary to require attribution for this image? This makes it considerably harder to use it - even if it's only a "choose your storage provider" screen, you have to add a visible attribution statement somewhere. In fact, I'm not even sure that the logo usage on https://remotestorage.io/ isn't currently violating license terms. So why not CC0?

Seeing the discussion in #2, this is completely unrelated to acceptable use of the remoteStorage brand. I could create my own SVG with the same visuals and CC-BY-SA would no longer apply. The terms by which you allow your brand to be used should be specified independently of the image license.

**Comment by raucao** [comment]
Afaik, the current logo is public domain, with zero restrictions. It would seem you found an outdated license statement.

**Comment by palant** [comment]
That license statement is right in this repository: https://github.com/remotestorage/design/blob/master/README.md#license

Also, https://github.com/remotestorage/design/issues/3#issuecomment-135711847 sort of implies that the license of the new logo is CC-BY again.

So where is a current license statement? It would be great to see this stated somewhere...

**Comment by raucao** [comment]
> Also, [#3 (comment)](https://github.com/remotestorage/design/issues/3#issuecomment-135711847) sort of implies that the license of the new logo is CC-BY again.

That comment was mostly about the as of yet non-existing logo typeface.

> So where is a current license statement? It would be great to see this stated somewhere...

As I said, I think you found an outdated statement. It would seem that we missed changing the statement, when the new logo was published. The new logo started out as a freelance job, sponsored by 5apps, and was finished up with help of community members at the time.
